### ISSUE TITLE
Add a basic initiative tracker

### ISSUE THREAD

**Issue by BodrickLight** [dndplayer/dnd-player#6]

**Comment by chrisella** [comment]
I'll aim to get this in for this coming Thursday, based around the ideas we discussed this lunch.

- A Linear display horizontally at the top
- Show PC / NPC tokens
- Allow quick HP modification by clicking on tokens in the tracker
- Show active turn
- Allow DM to move to next turn to move the tracker on for everyone.
- Perhaps when it becomes a persons turn, it could not only show them active at the top but also so something more (Flash screen, play sound, popup message).

**Comment by BodrickLight** [comment]
- Button to close the tracker and remove everyone from it (dm only)
- Show initiative number on/above token
- Show AC on/below token (dm only)
- Order by initiative descending (+ 0.1 * dex modifier)

**Comment by chrisella** [comment]
That final point (Order by init desc) is done, but the bit about + 0.1 * dex mod, what is that and is that important ? Do I need to add that in too ?

**Comment by BodrickLight** [comment]
Basically ties should be broken in favour of the character with the highest dexterity. Roll20 does this by adding 0.1 * each characters dex modifier to their roll (not that we have to do it that way if there's a better way!)

**Comment by chrisella** [comment]
Extra commit 5f29a80d964303edade86f090d32d0268c69d722

This is pretty much done, at-least well enough to use in the short/medium term.

**Comment by chrisella** [comment]
Change NPCs in the initiative data to reference a tokenId instead of npcId.
Tokens in-turn reference an npc anyway so it's still possible to get image etc.
This way we have the unique health for a token.
When doing this short term just continuing to have the init tracker global is probably easiest, but to preserve token refs without causing errors the init tracker data should probably exist per map, food for thought.
